baseURL = 'https://bcheek.dev/'
locale = 'en-us'
title = 'Brayden Cheek'
theme = 'PaperMod'

[menu]
    [[menu.main]]
        identifier = 'software'
        name = 'Software'
        url = '/software/'
    [[menu.main]]
        identifier = 'music'
        name = 'Music'
        url = '/music/'
    [[menu.main]]
        identifier = 'blog'
        name = 'Blog'
        url = '/blog/'
    [[menu.main]]
        identifier = 'about'
        name = 'About'
        url = '/about/'

[params]
    [params.profileMode]
        enabled = true
        title = "Hi, I'm Brayden"
        subtitle = "I enjoy building software and making music. See some of my work:"

        [[params.socialIcons]]
            name = "gitlab"
            url = "test"
        [[params.socialIcons]]
            name = "instagram"
            url = "test"

        [[params.profileMode.imageLinks]]
            name = "SlidePositions"
            desc = "desc"
            url = "google.com"
            image = "https://i.sstatic.net/yZlqh.png"
        [[params.profileMode.imageLinks]]
            name = "Music"
            desc = "desc"
            url = "google.com"
            image = "https://i.sstatic.net/yZlqh.png"

